baseURL = 'https://pankti.palashbauri.in/'
languageCode = 'en-us'
title = 'Pankti Programming Language'
theme = "hugo-book"


[markup]
[markup.highlight]
	style = "igor"
	lineNos = true
	lineNumbersInTable = false
[markup.goldmark.renderer]
	unsafe = true

[languages]
[languages.bn]
	title = "পঙক্তি প্রোগ্রামিং ভাষা"
	languageName = 'Bengali'
	contentDir = 'content.bn'
[languages.bn.params]
	weigth = 2
[languages.en]
	languageName = 'English'
	contentDir = 'content.en'
[languages.en.params]
	weigth = 1

[params]
	BookRepo = 'https://github.com/bauripalash/pankti-web'

